
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "1234"
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mysite_development
  username: postgres
  password: "1234"


test:
  <<: *default
  database: mysite_test
  username: postgres
  password: "1234"



primary_production: &primary_production
  <<: *default
  database: mysite_pzos
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
  password: h71n9uYh4LfJXDuyZHnSljINjVUH2QUa
  host: dpg-ctt5o5jv2p9s738fnop0-a.oregon-postgres.render.com
  port: 5432

production:
  primary:
    <<: *primary_production
  cache:
    <<: *primary_production
    database: mysite_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mysite_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mysite_production_cable
    migrations_paths: db/cable_migrate
